<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="arduino_robot_arm">

  <!-- xacro:property name="pi" value="3.14159"/-->
  <xacro:property name="deg" value="${pi/180.0}"/>
  <xacro:property name="scale" value="0.00098"/>
  <xacro:property name="scale_large" value="0.00391"/>

  <xacro:property name="base_length" value="0.32" />
  <xacro:property name="base_width" value="0.25" />
  <xacro:property name="base_height" value="0.25" />
  <xacro:property name="wheel_radius" value="0.075" />
  <xacro:property name="wheel_length" value="0.05" />

  <xacro:include filename="common_properties.xacro" />
  <xacro:include filename="mobile_base_gazebo.xacro" />
  <xacro:include filename="arduino_arm_gazebo.xacro" />

  <link name="base">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="0.01" />
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001" />
    </inertial>
    <visual name="Base">
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <geometry>
        <mesh filename="package://mycobot_description/meshes/stl/Base.stl" scale="${scale} ${scale} ${scale}" />
      </geometry>
    </visual>
    <collision name="Base">
      <origin xyz="-0.0029 0.00016 0.01165" rpy="${pi} 0 0" />
      <geometry>
        <cylinder radius="0.0592" length="0.05469" />
      </geometry>
    </collision>
  </link>

  <link name="waist">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="0.001" />
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001" />
    </inertial>
    <visual name="Waist">
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <geometry>
        <mesh filename="package://mycobot_description/meshes/stl/Waist.stl" scale="${scale} ${scale} ${scale}" />
      </geometry>
    </visual>
    <collision name="Waist.000">
      <origin xyz="8e-05 -8e-05 0.00021" rpy="${pi/2} 0 0" />
      <geometry>
        <mesh filename="package://mycobot_description/meshes/stl/Waist.001.stl" scale="0.00391 0.00391 0.00391" />
      </geometry>
    </collision>
  </link>

  <link name="arm1">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="0.001" />
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001" />
    </inertial>
    <visual name="Arm 01">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://mycobot_description/meshes/stl/Arm_01.stl" scale="${scale} ${scale} ${scale}" />
      </geometry>
    </visual>
    <collision name="Arm 01">
      <origin xyz="-0.00032 0.05624 0.00439" rpy="0 0 0" />
      <geometry>
        <!-- box size="0.04221 0.16277 0.02051" /-->
        <mesh filename="package://mycobot_description/meshes/stl/Arm_01.stl" scale="${scale} ${scale} ${scale}" />
      </geometry>
    </collision>
  </link>

  <link name="arm2">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="0.001" />
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001" />
    </inertial>
    <visual name="Arm 02">
      <origin xyz="0 0 0" rpy="-1.48894 -1.57209 1.57068" />
      <geometry>
        <mesh filename="package://mycobot_description/meshes/stl/Arm_02.stl" scale="${scale} ${scale} ${scale}" />
      </geometry>
    </visual>
    <collision name="Arm 02">
      <origin xyz="-0.00436 0.05687 0.01375" rpy="-1.4891 -1.57209 1.57084" />
      <geometry>
        <box size="0.02681 0.16397 0.0384" />
      </geometry>
    </collision>
  </link>

  <link name="gripper">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="0.001" />
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001" />
    </inertial>
    <visual name="Gripper">
      <origin xyz="0 0 0" rpy="0.60119 -1.56847 -1.57014" />
      <geometry>
        <mesh filename="package://mycobot_description/meshes/stl/Gripper.stl" scale="${scale_large} ${scale_large} ${scale_large}" />
      </geometry>
    </visual>
    <collision name="Gripper.000">
      <origin xyz="0.00024 -0.00025 0.00033" rpy="0.60128 -1.56847 -1.57014" />
      <geometry>
        <mesh filename="package://mycobot_description/meshes/stl/Gripper.001.stl" scale="${scale_large} ${scale_large} ${scale_large}" />
      </geometry>
    </collision>
  </link>

  <link name="base_footprint" />

  <link name="base_link">
      <visual>
          <geometry>
              <box size="${base_length} ${base_width} ${base_height}" />
          </geometry>
          <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
          <material name="blue" />
      </visual>
      <collision>
          <geometry>
              <box size="${base_length} ${base_width} ${base_height}" />
          </geometry>
          <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
      </collision>
      <xacro:box_inertia m="5.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}"
                        xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
  </link>

  <xacro:macro name="wheel_link" params="prefix">
    <link name="${prefix}_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${2*wheel_radius}" h="${2*wheel_length}" 
                                xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
    </link>
  </xacro:macro>

  <xacro:wheel_link prefix="right" />
  <xacro:wheel_link prefix="left" />

  <link name="caster_wheel_link">
      <visual>
          <geometry>
              <sphere radius="${wheel_radius / 2.0}" />
          </geometry>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <material name="grey" />
      </visual>
      <collision>
          <geometry>
              <sphere radius="${wheel_radius / 2.0}" />
          </geometry>
          <origin xyz="0 0 0" rpy="0 0 0" />
      </collision>
      <xacro:sphere_inertia m="0.5" r="${2*wheel_radius / 2.0}"
                            xyz="0 0 0" rpy="0 0 0" />
  </link>





  <joint name="base_joint" type="revolute">
    <origin xyz="-0.00345 -1e-05 0.04449" rpy="0 0 0" />
    <parent link="base" />
    <child link="waist" />
    <axis xyz="0 0 1.0" />
    <limit lower="-1.571" upper="1.571" effort="1000.0" velocity="1.0" />
  </joint>

  <joint name="shoulder" type="revolute">
    <origin xyz="0.00396 0.01369 0.03521" rpy="${pi/2} 0.03778 ${pi/2}" />
    <parent link="waist" />
    <child link="arm1" />
    <axis xyz="0 0 1.0" />
    <limit lower="-1.571" upper="1.571" effort="1000.0" velocity="1.0" />
  </joint>

  <joint name="elbow" type="revolute">
    <origin xyz="-7e-05 0.11689 -0.00792" rpy="-0.0013 ${pi} 0.03778" />
    <parent link="arm1" />
    <child link="arm2" />
    <axis xyz="0 0 1.0" />
    <limit lower="-1.57" upper="1.57" effort="1000.0" velocity="1.0" />
  </joint>

  <joint name="wrist" type="revolute">
    <origin xyz="-0.00922 0.12639 -0.00514" rpy="3.14056 0 0" />
    <parent link="arm2" />
    <child link="gripper" />
    <axis xyz="0 0 1.0" />
    <limit lower="-1.57" upper="1.57" effort="1000.0" velocity="1.0" />
  </joint>


    <joint name="mobile_base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link" />
        <origin xyz="${base_length / 3.0} 0 ${-wheel_radius / 2.0}" rpy="0 0 0" />
    </joint>

    <joint name="mobile_base_arm_joint" type="fixed">
        <parent link="base_link" />
        <child link="base" />
        <origin xyz="${base_length / 4.0} 0 ${base_height}" rpy="0.0 0.0 1.57" />
    </joint>



  <!-- ROS2 Humble Transmission -->
  <!--transmission name="trans_base_joint">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="base_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="base_joint_motor">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="trans_shoulder">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="shoulder">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="shoulder_motor">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="trans_elbow">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="elbow">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="elbow_motor">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="trans_wrist">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wrist">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="wrist_motor">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission-->

  <!-- Gazebo Plugin for ROS2 -->
  <!--gazebo>
    <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
      <robotNamespace>/</robotNamespace>
    </plugin>
  </gazebo>

  <gazebo>
        <plugin name="joint_state_publisher_controller"
                filename="libgazebo_ros_joint_state_publisher.so">
            <update_rate>10</update_rate>
            <joint_name>base_joint</joint_name>
            <joint_name>shoulder</joint_name>
            <joint_name>elbow</joint_name>
            <joint_name>wrist</joint_name>
        </plugin>
    </gazebo>

    <gazebo>
        <plugin name="joint_pose_trajectory_controller"
                filename="libgazebo_ros_joint_pose_trajectory.so">
            <update_rate>2</update_rate>
        </plugin>
    </gazebo-->

</robot>
